spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: airports
          uri: lb://micro-airport-location
          predicates:
            - Path=/airports/**
        - id: cities
          uri: lb://micro-airport-location
          predicates:
            - Path=/cities/**
        - id: countries
          uri: lb://micro-airport-location
          predicates:
            - Path=/countries/**

server:
  port: 8765

eureka:
  client:
    service-host: localhost
    service-url:
      defaultZone: http://${eureka.client.service-host}:8761/eureka
