spring:
  application:
    name: api-gateway

  #Cloud
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: airports
          uri: lb://micro-airport-location
          predicates:
            - Path=/airports/**
        - id: cities
          uri: lb://micro-airport-location
          predicates:
            - Path=/cities/**
        - id: countries
          uri: lb://micro-airport-location
          predicates:
            - Path=/countries/**
        - id: refresh
          uri: lb://authentication-service
          predicates:
            - Path=/refresh
        - id: password
          uri: lb://authentication-service
          predicates:
            - Path=/password/**
        - id: extract-username
          uri: lb://authentication-service
          predicates:
            - Path=/extract-username
        - id: valid-access-token
          uri: lb://authentication-service
          predicates:
            - Path=/valid-access-token
        - id: generate-token
          uri: lb://authentication-service
          predicates:
            - Path=/generate-token/**
        - id: users
          uri: lb://micro-airport-core
          predicates:
            - Path=/users/**
        - id: airlines
          uri: lb://airline-service
          predicates:
            - Path=/airlines/**

server:
  port: 8765

eureka:
  client:
    service-host: localhost
    service-url:
      defaultZone: http://${eureka.client.service-host}:8761/eureka/
